### ISSUE TITLE
Pooled variance in the denominator when estimand is "ATE"

### ISSUE THREAD

**Issue by waaally** [cran/cobalt#3]
Hi, it seems that for pooled variance as the denominator in bal.tab(), the treated and untreated are weighted equally. In my case, I have a hugely imbalanced sample, e.g. <1% treated. Eventually I'm using IPTW and I would like to assess how the balance improves with those weights. Cohen's d for an imbalanced sample weighs the pooled variance, i.e. pooled variance= √([(𝑛1−1)*𝑠1^2+(𝑛2−1)*𝑠2^2] / (𝑛1+𝑛2−2)).

I'm wondering in the case of evaluating covariate balance of a hugely imbalanced sample, should the more appropriate pooled variance in the denominator be half treated variance-half control variance, or should it weigh the control group more?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by waaally** [comment]
Hi,

I see thanks! I've emailed the author.
